//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGestorTareas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> Puntos { get; set; }
        public string NivelDificultad { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
        public int Castigo_Id { get; set; }
    
        public virtual Castigo Castigo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
